using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Generates the reference corner list (answer key) based on flip-flop output events.
/// Interacts with <see cref="LevelJsonLoader"/> to parse signal events and <see cref="LevelManager"/> for level boundaries.
/// </summary>
public class GabaritoGenerator
{
    #region Fields & Properties

    /// <summary>
    /// World Y position corresponding to logical LOW state (0).
    /// </summary>
    public readonly float LowY;

    /// <summary>
    /// World Y position corresponding to logical HIGH state (1).
    /// </summary>
    public readonly float HighY;

    /// <summary>
    /// List of reference corners generated by the last successful call to <see cref="Generate"/> or <see cref="BuildFromEvents"/>.
    /// Guaranteed not to be null after instantiation.
    /// </summary>
    public List<Vector3> CorrectCorners { get; private set; } = new();

    #endregion

    #region Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="GabaritoGenerator"/> class with defined Y bounds for LOW and HIGH logic states.
    /// </summary>
    /// <param name="lowY">World Y position for logical LOW (0).</param>
    /// <param name="highY">World Y position for logical HIGH (1).</param>
    public GabaritoGenerator(float lowY, float highY)
    {
        LowY = lowY;
        HighY = highY;
    }

    #endregion

    #region Public Methods

    /// <summary>
    /// Finds the <see cref="LevelJsonLoader"/> in the scene and generates the reference path corners.
    /// Typically invoked once during initialization from <see cref="PathVerifier"/>.
    /// </summary>
    public void Generate()
    {
        var loader = Object.FindAnyObjectByType<LevelJsonLoader>();
        if (loader == null)
        {
            Debug.LogError("[GabaritoGenerator] LevelJsonLoader not found in scene.");
            CorrectCorners = new List<Vector3>();
            return;
        }

        var events = loader.ComputeOutputEventsFromParsedSignals();
        BuildFromEvents(events, initialX: 0f, initialState: false);
    }

    /// <summary>
    /// Reconstructs the reference corners from a list of calculated signal events.
    /// Can be called externally for testing or editor previews.
    /// Interacts with <see cref="LevelManager"/> to query phase end X boundaries.
    /// </summary>
    /// <param name="events">List of signal transition events containing X coordinate and logical output value.</param>
    /// <param name="initialX">Starting X world coordinate of the path (defaults to 0).</param>
    /// <param name="initialState">Initial logical output state (false = LOW, true = HIGH).</param>
    public void BuildFromEvents(
        List<PathVerifier.SignalEvent> events,
        float initialX = 0f,
        bool initialState = false)
    {
        CorrectCorners = new List<Vector3>();
        bool qState = initialState;
        float startY = qState ? HighY : LowY;

        CorrectCorners.Add(new Vector3(initialX, startY, 0f));

        if (events == null || events.Count == 0)
        {
            float phaseEnd = LevelManager.Instance != null ? LevelManager.Instance.phaseEndX : 0f;
            CorrectCorners.Add(new Vector3(phaseEnd, startY, 0f));
            return;
        }

        events.Sort((a, b) => a.x.CompareTo(b.x));

        foreach (var ev in events)
        {
            float previousY = qState ? HighY : LowY;
            CorrectCorners.Add(new Vector3(ev.x, previousY, 0f));

            if (ev.value != qState)
            {
                float currentY = ev.value ? HighY : LowY;
                CorrectCorners.Add(new Vector3(ev.x, currentY, 0f));
                qState = ev.value;
            }
        }

        float endX = LevelManager.Instance != null
            ? LevelManager.Instance.phaseEndX
            : events[events.Count - 1].x;
        CorrectCorners.Add(new Vector3(endX, qState ? HighY : LowY, 0f));

        RemoveDuplicatesAndCollinear();
    }

    #endregion

    #region Private Methods

    /// <summary>
    /// Filters out duplicate points and redundant collinear points along flat line segments.
    /// </summary>
    private void RemoveDuplicatesAndCollinear()
    {
        for (int i = CorrectCorners.Count - 1; i > 0; i--)
        {
            if (Vector3.Distance(CorrectCorners[i], CorrectCorners[i - 1]) < 0.01f)
            {
                CorrectCorners.RemoveAt(i);
                continue;
            }

            if (i == 0 || i >= CorrectCorners.Count - 1) continue;

            if (CorrectCorners[i - 1].y == CorrectCorners[i].y &&
                CorrectCorners[i + 1].y == CorrectCorners[i].y)
            {
                CorrectCorners.RemoveAt(i);
            }
        }
    }

    #endregion
}
