using System.Collections.Generic;
using UnityEngine;

#region Data Structures

/// <summary>
/// Immutable result structure produced by <see cref="PathChecker.Evaluate"/>.
/// Contains accuracy statistics, missed corner locations, and per-corner verification statuses.
/// </summary>
public readonly struct PathCheckResult
{
    /// <summary>
    /// True if all reference corners were successfully hit by the player's path.
    /// </summary>
    public readonly bool IsCorrect;

    /// <summary>
    /// Number of reference path segments covered by the player's path.
    /// </summary>
    public readonly int CoveredSegments;

    /// <summary>
    /// Total number of reference path segments (calculated as reference corner count minus 1).
    /// </summary>
    public readonly int GabaritoTotal;

    /// <summary>
    /// List of reference corner coordinates that were missed by the player.
    /// </summary>
    public readonly IReadOnlyList<Vector3> MissedCorners;

    /// <summary>
    /// Boolean verification result per reference corner (true = hit, false = missed).
    /// </summary>
    public readonly IReadOnlyList<bool> CornerChecks;

    /// <summary>
    /// Initializes a new instance of the <see cref="PathCheckResult"/> struct.
    /// </summary>
    /// <param name="isCorrect">Whether all corners were hit.</param>
    /// <param name="coveredSegments">Count of covered reference segments.</param>
    /// <param name="gabaritoTotal">Total segment count in reference path.</param>
    /// <param name="missedCorners">Collection of missed corner points.</param>
    /// <param name="cornerChecks">Per-corner hit boolean flags.</param>
    public PathCheckResult(
        bool isCorrect,
        int coveredSegments,
        int gabaritoTotal,
        List<Vector3> missedCorners,
        List<bool> cornerChecks)
    {
        IsCorrect = isCorrect;
        CoveredSegments = coveredSegments;
        GabaritoTotal = gabaritoTotal;
        MissedCorners = missedCorners.AsReadOnly();
        CornerChecks = cornerChecks.AsReadOnly();
    }
}

#endregion

/// <summary>
/// Evaluates whether the player's recorded path (<see cref="SignalPath"/>) matches the expected reference corners (<see cref="GabaritoGenerator"/>).
/// Stateless evaluation module that produces a <see cref="PathCheckResult"/>.
/// </summary>
public class PathChecker
{
    #region Fields

    /// <summary>
    /// Maximum world-unit distance allowed to consider a reference corner as hit.
    /// </summary>
    private readonly float cornerTolerance;

    /// <summary>
    /// Flag indicating whether detailed evaluation messages should be printed to the Unity console.
    /// </summary>
    private readonly bool enableDebugLogs;

    #endregion

    #region Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="PathChecker"/> class with tolerance and logging options.
    /// </summary>
    /// <param name="cornerTolerance">Maximum distance tolerance for hitting corners.</param>
    /// <param name="enableDebugLogs">Whether to log detailed verification info.</param>
    public PathChecker(float cornerTolerance, bool enableDebugLogs = false)
    {
        this.cornerTolerance = cornerTolerance;
        this.enableDebugLogs = enableDebugLogs;
    }

    #endregion

    #region Public Verification API

    /// <summary>
    /// Evaluates the player's path against the reference corners (answer key).
    /// Receives corners generated by <see cref="GabaritoGenerator"/> and path points recorded by <see cref="SignalPath"/>.
    /// </summary>
    /// <param name="correctCorners">List of reference solution corners.</param>
    /// <param name="playerPath">List of recorded player path coordinates.</param>
    /// <returns>A <see cref="PathCheckResult"/> containing detailed match stats.</returns>
    public PathCheckResult Evaluate(List<Vector3> correctCorners, List<Vector3> playerPath)
    {
        var missedCorners = new List<Vector3>();
        var cornerChecks = new List<bool>();

        if (enableDebugLogs)
        {
            Debug.Log("<color=cyan>[PathChecker] Starting path evaluation</color>");
            Debug.Log($"  Player points: {playerPath.Count}");
            Debug.Log($"  Reference corners: {correctCorners.Count}");
            Debug.Log($"  Tolerance: {cornerTolerance}");
        }

        int cornerIndex = 0;
        foreach (Vector3 correctCorner in correctCorners)
        {
            bool hit = EvaluateCornerHit(correctCorner, playerPath, out float minDist, out Vector3 closest);
            cornerChecks.Add(hit);

            if (!hit)
            {
                missedCorners.Add(correctCorner);
                if (enableDebugLogs)
                    Debug.LogWarning($"  <color=red>✗ Corner #{cornerIndex} MISSED:</color> Pos={correctCorner} | Min Distance={minDist:F2} | Closest Point={closest}");
            }
            else if (enableDebugLogs)
            {
                Debug.Log($"  <color=green>✓ Corner #{cornerIndex} OK:</color> Pos={correctCorner} | Distance={minDist:F2}");
            }

            cornerIndex++;
        }

        bool isCorrect = !cornerChecks.Contains(false);
        int gabaritoTotal = correctCorners.Count - 1;
        int coveredSegments = CountCoveredSegments(correctCorners, playerPath);

        if (enableDebugLogs)
        {
            int correct = cornerChecks.FindAll(x => x).Count;
            Debug.Log($"<color=yellow>[PathChecker] Result: {correct}/{cornerChecks.Count} corners hit</color>");
        }

        return new PathCheckResult(isCorrect, coveredSegments, gabaritoTotal, missedCorners, cornerChecks);
    }

    #endregion

    #region Private Helper Methods

    /// <summary>
    /// Checks if a single reference corner was reached by any line segment in the player's path within tolerance.
    /// </summary>
    /// <param name="corner">Target reference corner coordinate.</param>
    /// <param name="playerPath">Player path points.</param>
    /// <param name="minDistance">Out parameter returning the minimum calculated distance to the path.</param>
    /// <param name="closestPoint">Out parameter returning the closest point on the player path.</param>
    /// <returns>True if the closest point is within <see cref="cornerTolerance"/>.</returns>
    private bool EvaluateCornerHit(
        Vector3 corner,
        List<Vector3> playerPath,
        out float minDistance,
        out Vector3 closestPoint)
    {
        minDistance = float.MaxValue;
        closestPoint = Vector3.zero;
        bool wasHit = false;

        for (int i = 0; i < playerPath.Count - 1; i++)
        {
            Vector3 closest = FindClosestPointOnSegment(corner, playerPath[i], playerPath[i + 1]);
            float distance = Vector3.Distance(closest, corner);

            if (distance < minDistance)
            {
                minDistance = distance;
                closestPoint = closest;
            }

            if (distance <= cornerTolerance)
            {
                wasHit = true;
                break;
            }
        }

        return wasHit;
    }

    /// <summary>
    /// Counts how many reference segments have their midpoint sufficiently close (<= tolerance) to the player path.
    /// </summary>
    /// <param name="correctCorners">Reference corners.</param>
    /// <param name="playerPath">Player path points.</param>
    /// <returns>The number of covered reference segments.</returns>
    private int CountCoveredSegments(List<Vector3> correctCorners, List<Vector3> playerPath)
    {
        int covered = 0;
        for (int i = 0; i < correctCorners.Count - 1; i++)
        {
            Vector3 midpoint = (correctCorners[i] + correctCorners[i + 1]) / 2f;
            Vector3 closest = FindClosestPointOnFullPath(midpoint, playerPath);
            if (Vector3.Distance(midpoint, closest) <= cornerTolerance)
                covered++;
        }
        return covered;
    }

    /// <summary>
    /// Finds the closest point on the entire player path to a given target position.
    /// </summary>
    /// <param name="target">Target point in world space.</param>
    /// <param name="path">List of path points.</param>
    /// <returns>The nearest point on any segment of the path.</returns>
    private Vector3 FindClosestPointOnFullPath(Vector3 target, List<Vector3> path)
    {
        if (path.Count == 0) return Vector3.zero;
        if (path.Count == 1) return path[0];

        Vector3 best = path[0];
        float bestSqr = (best - target).sqrMagnitude;

        for (int i = 0; i < path.Count - 1; i++)
        {
            Vector3 candidate = FindClosestPointOnSegment(target, path[i], path[i + 1]);
            float sqr = (candidate - target).sqrMagnitude;
            if (sqr < bestSqr) { bestSqr = sqr; best = candidate; }
        }
        return best;
    }

    /// <summary>
    /// Calculates the point on segment AB that is nearest to point P.
    /// </summary>
    /// <param name="point">Point P.</param>
    /// <param name="a">Segment start point A.</param>
    /// <param name="b">Segment end point B.</param>
    /// <returns>The closest projection point along segment AB.</returns>
    private static Vector3 FindClosestPointOnSegment(Vector3 point, Vector3 a, Vector3 b)
    {
        Vector3 dir = b - a;
        float lenSqr = dir.sqrMagnitude;
        if (lenSqr < 0.0001f) return a;
        float t = Mathf.Clamp01(Vector3.Dot(point - a, dir) / lenSqr);
        return a + dir * t;
    }

    #endregion
}
