name: Version & README updater

on:
  push:
    branches:
      - main # ou master
  workflow_dispatch:

jobs:
  release:
    name: Versioning & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Essencial para ler e escrever no repo
      issues: write
      pull-requests: write
      id-token: write

    steps:
      # 1. Faz o checkout do código do seu repositório
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para analisar todo o histórico de commits

      # 3. Determina a próxima versão com base em Conventional Commits
      - name: Generate Changelog and Version
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: true # Não queremos que ele crie um arquivo de versão, nós mesmos vamos atualizar

      # 4. Cria um Release simples com a nova versão (sem anexos)
      - name: Create GitHub Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: Release ${{ steps.changelog.outputs.version }}
          body: "Automated release created by CI"
  
